### ISSUE TITLE
Utilization time error in description pdf example output

### ISSUE THREAD

**Issue by efehan-atici-2016700186** [nozlemozcan/CMPE250_2017Fall_Project2#2]
For the example given in the project description,

There are 6 cashiers with orders,

id | Arrival | Order Time | Cashier Leave Time
---|--------|--------------|----------------------
1 | 0 | 20.75 | 20.75
2 | 3.21 | 22.47 | 25.68
3 | 5.17 | 19.83 | 25.00
4 | 8.16 | 21.10 | 29.26
5 | 9.54 | 26.05 | 35.59
6 | 10.32 | 11.10 | 21.42
7 | 16.47 | 34.68 | ????
8 | 23.13 | 17.33 | ????
9 | 27.52 | 40.68 | ????
10 | 28.08 | 16.80 | ????

Without implementing to code, just by thinking we can see, first 6 orders will employ the cashiers and 7th order will be in the queue. The first cashier to finish its order is the 1st one, so the cashier 1 will take 7's order. Cashier 1's utilization time will be: 20.75 + 34.68 = 55.43, considering overall runtime 137.52 its utilization is 55.43/137.52 = 0.40. 

This is right, however for cashier 2, its order won't end until 25.68. Cashier 6 will end at 10.32+11.10 = 21.42, and cashier 3 will end at 5.17+19.83 = 25.00, so these two will take customer 8,9 and cashier 2 will take customer 10. 

Now the running time of cashier 2 will be sum of the order time of 2nd customer and 10th customer which is: 22.47+16.80 = 39.27. Which is 39.27/137.52 = 0.29~. But in the pdf it says 0.46. 

Implementation Details state that utilization time should be:

![acrobat_2017-11-13_12-34-25](https://user-images.githubusercontent.com/32371422/32718731-102dcbc6-c86f-11e7-88cf-2ae1fb792fc4.png)

By this definition, cashier 2 and 3's utilization times are wrong on the example on the pdf.

For cashier 3, customers are 3 and 9, order time will be 40.68 + 19.83 = 60.51, utilization: 60.51/137.52 = 0.44. But it says, 0.27 on the pdf.

**Comment by akoksal** [comment]
As stated in the project description, when customer arrives, it goes the available cashier with smallest id.

You missed a small point. When 9th customer arrives(in 27.52), cashier 2 is available as well as cashier 3. Customer 9 chooses the cashier with smallest id which is cashier 2.

**Comment by efehan-atici-2016700186** [comment]
Ah yes, I missed that, thanks for the response.

**Comment by akoksal** [comment]
As stated in the project description, when customer arrives, it goes the available cashier with smallest id.

You missed a small point. When 9th customer arrives(in 27.52), cashier 2 is available as well as cashier 3. Customer 9 chooses the cashier with smallest id which is cashier 2.
